SELECT
C.TABLE_CATALOG,
C.TABLE_SCHEMA,
C.TABLE_NAME,
C.COLUMN_NAME,
C.COLUMN_DEFAULT,
C.IS_NULLABLE,
C.DATA_TYPE,
C.CHARACTER_MAXIMUM_LENGTH,
C.CHARACTER_OCTET_LENGTH,
C.NUMERIC_PRECISION,
C.NUMERIC_SCALE,
A.CONSTRAINT_TYPE,
A.CHECK_CLAUSE
FROM INFORMATION_SCHEMA.COLUMNS C LEFT OUTER JOIN
(
SELECT
CCU.TABLE_CATALOG,
CCU.TABLE_SCHEMA,
CCU.TABLE_NAME,
CCU.COLUMN_NAME,
CT.CONSTRAINT_TYPE,
CHK.CHECK_CLAUSE
FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS CT
ON CCU.CONSTRAINT_NAME = CT.CONSTRAINT_NAME
LEFT OUTER JOIN INFORMATION_SCHEMA.CHECK_CONSTRAINTS CHK
ON CT.CONSTRAINT_NAME = CHK.CONSTRAINT_NAME
) A
ON A.COLUMN_NAME = C.COLUMN_NAME
AND A.TABLE_NAME = C.TABLE_NAME
AND A.TABLE_SCHEMA = C.TABLE_SCHEMA;