SELECT *
FROM OPENROWSET('ORAOLEDB.Oracle','MyOracleDatabase';'TestOracle';'Me4B0ss',
'
SELECT
COLUMN_NAME,
DATA_TYPE,
DATA_LENGTH,
CAST(DATA_PRECISION AS NUMBER(38,0)) AS DATA_PRECISION,
NULLABLE
FROM all_tab_columns
WHERE table_name=''SOURCEDATA''
')