SELECT
CO.TABLE_CATALOG
,CO.TABLE_SCHEMA
,CO.TABLE_NAME
,CO.COLUMN_NAME
,CO.ORDINAL_POSITION
,CO.COLUMN_DEFAULT
,CO.IS_NULLABLE
,CO.DATA_TYPE
,CO.CHARACTER_MAXIMUM_LENGTH
,CO.CHARACTER_OCTET_LENGTH
,CO.NUMERIC_PRECISION
,CO.NUMERIC_SCALE
,CO.CHARACTER_SET_NAME
,CO.COLUMN_TYPE
,CO.COLUMN_KEY
,KCU.CONSTRAINT_NAME
,KCU.REFERENCED_TABLE_NAME
,KCU.REFERENCED_COLUMN_NAME
FROM COLUMNS CO
LEFT JOIN KEY_COLUMN_USAGE KCU
ON CO.COLUMN_NAME = KCU.COLUMN_NAME
AND CO.TABLE_NAME = KCU.TABLE_NAME
AND CO.TABLE_SCHEMA = KCU.TABLE_SCHEMA;