BULK INSERT dbo.InvoiceBulkLoad
FROM 'C:\SQL2012DIRecipes\CH02\InvoiceBulkLoad.Txt'
WITH
(
FIELDTERMINATOR = ',',
ROWTERMINATOR = '\n',
FIRSTROW = 2,
KEEPNULLS,
KEEPIDENTITY,
FIRE_TRIGGERS,
CHECK_CONSTRAINTS
) ;